# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d5223e6a1b6091da87f46a310661293224da33c0bed0148581d50e770b13a761843a3aa0fd52d479314e8ba2c667889d2e2a9924bca5a37a39057f0dc82b8b65

test:
  secret_key_base: ceb1da64bbb6c2729442e69f600e5f72e3a0e9b7e8c939dc3870becfe9d867a61b68446199e074d3599a5d2e76858b4e9ed32a348f8c55dd4ae20254656f0d94

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
